

mxp:
	make -f Makefile-isa player=mxp clean
	make -f Makefile-isa player=mxp

jam:
	make -f Makefile-isa player=jam clean
	make -f Makefile-isa player=jam

all:
	make -f Makefile-isa player=mxp clean
	make -f Makefile-isa player=mxp
	make -f Makefile-isa player=jam clean
	make -f Makefile-isa player=jam

clean:
	make -f Makefile-isa player=mxp clean
	make -f Makefile-isa player=jam clean

