

all:
	make -f Makefile-bios player=mxp clean
	make -f Makefile-bios player=mxp 
	make -f Makefile-bios player=jam clean
	make -f Makefile-bios player=jam 
	make -f Makefile-isa player=mxp clean
	make -f Makefile-isa player=mxp 
	make -f Makefile-isa player=jam clean
	make -f Makefile-isa player=jam 

mxp:
	make -f Makefile-bios player=mxp clean
	make -f Makefile-bios player=mxp 
	make -f Makefile-isa player=mxp clean
	make -f Makefile-isa player=mxp 

jam:
	make -f Makefile-bios player=jam clean
	make -f Makefile-bios player=jam 
	make -f Makefile-isa player=jam clean
	make -f Makefile-isa player=jam 

clean:
	make -f Makefile-bios player=mxp clean
	make -f Makefile-bios player=jam clean
	make -f Makefile-isa player=mxp clean
	make -f Makefile-isa player=jam clean

